# Generated by Django 4.2.23 on 2025-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_account_link',
            field=models.TextField(blank=True, default='Not Provided', null=True),
        ),
    ]
