# Generated by Django 4.2.23 on 2025-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
